# Auto generated file, do not edit directly

msg_prio = {
    'HIGHEST': 0x0,
    'HIGH':    0x1,
    'MEDIUM':  0x2,
    'LOW':     0x3
}

msg_type = {
    'UNDEFINED':            0x000,
    'GENERAL_BOARD_STATUS': 0x001,
    'RESET_CMD':            0x002,
    'DEBUG_RAW':            0x003,
    'CONFIG_SET':           0x004,
    'CONFIG_STATUS':        0x005,
    'ACTUATOR_CMD':         0x006,
    'ACTUATOR_STATUS':      0x007,
    'ALT_ARM_CMD':          0x008,
    'ALT_ARM_STATUS':       0x009,
    'SENSOR_ANALOG16':      0x00A,
    'SENSOR_ANALOG32':      0x00B,
    'SENSOR_2D_ANALOG24':   0x00C,
    'SENSOR_3D_ANALOG16':   0x00D,
    'GPS_TIMESTAMP':        0x00E,
    'GPS_LATITUDE':         0x00F,
    'GPS_LONGITUDE':        0x010,
    'GPS_ALTITUDE':         0x011,
    'GPS_INFO':             0x012,
    'STREAM_STATUS':        0x013,
    'STREAM_DATA':          0x014,
    'STREAM_RETRY':         0x015,
    'LEDS_ON':              0x016,
    'LEDS_OFF':             0x017,
}

board_type_id = {
    'ANY':                  0x00,
    'INJECTOR':             0x01,
    'CAMERA':               0x02,
    'POWER':                0x03,
    'LOGGER':               0x04,
    'CANARD':               0x05,
    'TELEMETRY':            0x06,
    'GPS':                  0x07,
    'ALTIMETER':            0x08,
    'ARMING':               0x09,
    'PAYLOAD':              0x0A,
    'RLCS_GLS':             0x0B,
    'RLCS_RELAY':           0x0C,
    'DAQ':                  0x0D,
}

board_inst_id = {
    'ANY':    0x00,
    'GROUND': 0x01,
    'ROCKET': 0x02,
    'SIDE_LOOKING':0x03,
    'DOWN_LOOKING':0x04,
    'RECOVERY':    0x05,
    'RA_RAVEN':    0x06,
    'RA_STRATOLOGGER':0x07,
}

actuator_id = {
    'ACTUATOR_OX_INJECTOR_VALVE':      0x00,
    'ACTUATOR_FUEL_INJECTOR_VALVE':    0x01,
    'ACTUATOR_ROCKET_CHARGE_ENABLE':   0x02,
    'ACTUATOR_PAYLOAD_CHARGE_ENABLE':  0x03,
    'ACTUATOR_5V_RAIL_ROCKET':         0x04,
    'ACTUATOR_12V_RAIL_ROCKET':        0x05,
    'ACTUATOR_TELEMETRY':              0x06,
    'ACTUATOR_CAMERA_SIDE_LOOKING':    0x07,
    'ACTUATOR_CAMERA_DOWN_LOOKING':    0x08,
    'ACTUATOR_CAMERA_RECOVERY':        0x09,
    'ACTUATOR_CANARD_PAD_FILTER':      0x0A,
    'ACTUATOR_CANARD_5V_OUTPUT':       0x0B,
    'ACTUATOR_CANARD_LIPO_ON':         0x0C,
    'ACTUATOR_SRAD_ALT_ESTIMATOR_INIT':0x0D,
    'ACTUATOR_SRAD_ALT_GPS_RESET':     0x0E,
    'ACTUATOR_CAMERA_CAPTURE':         0x0F,
    'ACTUATOR_PAYLOAD_LOGGING_ENABLE': 0x10,
    'ACTUATOR_INJECTOR_BOARD_ACTUATOR_1':0x11,
    'ACTUATOR_INJECTOR_BOARD_ACTUATOR_2':0x12,
    'ACTUATOR_RLCS_RELAY_POWER':       0x13,
    'ACTUATOR_RLCS_RELAY_SELECT':      0x14,
    'ACTUATOR_PAYLOAD_LASER':          0x15,
    'ACTUATOR_PAYLOAD_PZT_ARM':        0x16,
}

actuator_state = {
    'ACT_STATE_ON':                    0x00,
    'ACT_STATE_OFF':                   0x01,
    'ACT_STATE_UNK':                   0x02,
    'ACT_STATE_ILLEGAL':               0x03,
}

altimeter_id = {
    'ALTIMETER_RAVEN':                 0x00,
    'ALTIMETER_STRATOLOGGER':          0x01,
    'ALTIMETER_SRAD':                  0x02,
}

alt_arm_state = {
    'ALT_ARM_STATE_DISARMED':          0x00,
    'ALT_ARM_STATE_ARMED':             0x01,
}

analog_sensor_id = {
    'SENSOR_5V_VOLT':                  0x00,
    'SENSOR_5V_CURR':                  0x01,
    'SENSOR_12V_VOLT':                 0x02,
    'SENSOR_12V_CURR':                 0x03,
    'SENSOR_CHARGE_VOLT':              0x04,
    'SENSOR_CHARGE_CURR':              0x05,
    'SENSOR_BATT_VOLT':                0x06,
    'SENSOR_BATT_CURR':                0x07,
    'SENSOR_RADIO_CURR':               0x08,
    'SENSOR_GPS_CURR':                 0x09,
    'SENSOR_LOCAL_CURR':               0x0A,
    'SENSOR_PT_CHANNEL_1':             0x0B,
    'SENSOR_PT_CHANNEL_2':             0x0C,
    'SENSOR_PT_CHANNEL_3':             0x0D,
    'SENSOR_PT_CHANNEL_4':             0x0E,
    'SENSOR_PT_CHANNEL_5':             0x0F,
    'SENSOR_PT_CHANNEL_6':             0x10,
    'SENSOR_PT_CHANNEL_7':             0x11,
    'SENSOR_PT_CHANNEL_8':             0x12,
    'SENSOR_PT_CHANNEL_9':             0x13,
    'SENSOR_PT_CHANNEL_10':            0x14,
    'SENSOR_HALL_CHANNEL_1':           0x15,
    'SENSOR_HALL_CHANNEL_2':           0x16,
    'SENSOR_HALL_CHANNEL_3':           0x17,
    'SENSOR_RA_BATT_VOLT_1':           0x18,
    'SENSOR_RA_BATT_VOLT_2':           0x19,
    'SENSOR_RA_BATT_CURR_1':           0x1A,
    'SENSOR_RA_BATT_CURR_2':           0x1B,
    'SENSOR_RA_MAG_VOLT_1':            0x1C,
    'SENSOR_RA_MAG_VOLT_2':            0x1D,
    'SENSOR_FPS':                      0x1E,
    'SENSOR_PAYLOAD_LIM_1':            0x1F,
    'SENSOR_PAYLOAD_LIM_2':            0x20,
    'SENSOR_PAYLOAD_SERVO_DIRECTION':  0x21,
    'SENSOR_PAYLOAD_INFRARED':         0x22,
    'SENSOR_INJECTOR_BOARD_TEMP_1':    0x23,
    'SENSOR_INJECTOR_BOARD_TEMP_2':    0x24,
    'SENSOR_INJECTOR_BOARD_TEMP_3':    0x25,
    'SENSOR_RLCS_RELAY_OUTPUT_VOLT_A': 0x26,
    'SENSOR_RLCS_RELAY_OUTPUT_VOLT_B': 0x27,
    'SENSOR_RLCS_RELAY_OUTPUT_CURR_A': 0x28,
    'SENSOR_RLCS_RELAY_OUTPUT_CURR_B': 0x29,
    'SENSOR_RLCS_RELAY_LIM_VOLT_A':    0x2A,
    'SENSOR_RLCS_RELAY_LIM_VOLT_B':    0x2B,
    'SENSOR_LOG_WRITTEN_SIZE':         0x2C,
    'SENSOR_SD_LOG_FILE_NAME':         0x2D,
    'SENSOR_SD_USED':                  0x2E,
    'SENSOR_SD_FREE':                  0x2F,
    'SENSOR_FLASH_LOG_FILE_NAME':      0x30,
    'SENSOR_FLASH_USED':               0x31,
    'SENSOR_FLASH_FREE':               0x32,
    'SENSOR_CANARD_CTRL_CMD_ANGLE':    0x33,
    'SENSOR_CANARD_CTRL_COEFF_LIFT':   0x34,
    'SENSOR_CANARD_MTI630_BARO_0':     0x35,
    'SENSOR_CANARD_MTI630_BARO_1':     0x36,
    'SENSOR_CANARD_MTI630_EST_ALT':    0x37,
    'SENSOR_CANARD_ADXRS649_GYRO':     0x38,
    'SENSOR_CANARD_SERVO_ANGLE':       0x39,
    'SENSOR_CANARD_SERVO_CURR':        0x3A,
    'SENSOR_CANARD_SERVO_TEMP':        0x3B,
    'SENSOR_PAYLOAD_SENSOR_CURR_READING':0x3C,
}

dem_2d_sensor_id = {
    'DEM_2D_SENSOR_CANARD_NAV_VEL_ANGLE_VEL_X':0x00,
    'DEM_2D_SENSOR_CANARD_NAV_VEL_ANGLE_VEL_Y':0x01,
    'DEM_2D_SENSOR_CANARD_NAV_VEL_ANGLE_VEL_Z':0x02,
    'DEM_2D_SENSOR_CANARD_MS5611_BARO_TEMP':0x03,
}

dem_3d_sensor_id = {
    'DEM_3D_SENSOR_CANARD_NAV_ORIENTATION_QUAT_QX_QY_QZ':0x00,
    'DEM_3D_SENSOR_CANARD_NAV_ORIENTATION_QUAT_QW_ALT_VARNORM':0x01,
    'DEM_3D_SENSOR_CANARD_LSM6DSV32X_ACCEL':0x02,
    'DEM_3D_SENSOR_CANARD_LSM6DSV32X_GYRO':0x03,
    'DEM_3D_SENSOR_CANARD_LSM303AGR_ACCEL':0x04,
    'DEM_3D_SENSOR_CANARD_LSM303AGR_MAG':0x05,
    'DEM_3D_SENSOR_CANARD_MTI630_ACCEL':0x06,
    'DEM_3D_SENSOR_CANARD_MTI630_GYRO':0x07,
    'DEM_3D_SENSOR_CANARD_MTI630_MAG': 0x08,
    'DEM_3D_SENSOR_CANARD_MTI630_EST_ORIENTATION':0x09,
    'DEM_3D_SENSOR_CANARD_MTI630_EST_ANGLE_VEL':0x0A,
    'DEM_3D_SENSOR_CANARD_MTI630_EST_VEL':0x0B,
    'DEM_3D_SENSOR_CANARD_ADXL380_ACCEL':0x0C,
}

board_error_bitfield_offset = {
    'E_5V_OVER_CURRENT':   0x00,
    'E_5V_OVER_VOLTAGE':   0x01,
    'E_5V_UNDER_VOLTAGE':  0x02,
    'E_12V_OVER_CURRENT':  0x03,
    'E_12V_OVER_VOLTAGE':  0x04,
    'E_12V_UNDER_VOLTAGE': 0x05,
    'E_BATT_OVER_CURRENT': 0x06,
    'E_BATT_OVER_VOLTAGE': 0x07,
    'E_BATT_UNDER_VOLTAGE':0x08,
    'E_MOTOR_OVER_CURRENT':0x09,
    'E_IO_ERROR':          0x0A,
    'E_FS_ERROR':          0x0B,
    'E_WATCHDOG_TIMEOUT':  0x0C,
    'E_12V_EFUSE_FAULT':   0x0D,
    'E_5V_EFUSE_FAULT':    0x0E,
    'E_PT_OUT_OF_RANGE':   0x0F,
}

