name: Run Lint

# Runs on pushes to pull request
on: pull_request

jobs:
  # Build job
  build:
    name: Compile and Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install basedpyright
        run: pip install --user basedpyright
      - name: Run basedpyright
        run: basedpyright .
        working-directory: parsley
